version: "3.1"
services:
  db:
    container_name: custom_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_organization
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
